# Fetching from node version 25 image
FROM node:25

# Setting up the work directory
WORKDIR /server

# Copy package.json and package-lock.json
COPY package*.json ./

# Installing dependencies
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD ["node", "app.js"]

# Exposing server port
EXPOSE 3000